# Generated by Django 4.2.19 on 2025-02-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='studentid',
        ),
    ]
