# Generated by Django 4.2.19 on 2025-02-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_student_id_user_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='student_id',
            new_name='studentid',
        ),
    ]
